# Generated by Django 5.2 on 2025-05-08 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0002_produit_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='category',
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Produits.categorie'),
            preserve_default=False,
        ),
    ]
