# Generated by Django 5.2 on 2025-05-26 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0003_remove_produit_category_produit_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produits.customer'),
        ),
    ]
